# Generated by Django 3.0.1 on 2020-01-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='orgname',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
