# Generated by Django 3.0.1 on 2020-01-20 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytrip', '0004_events_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='org',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='lan',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='lat',
            field=models.FloatField(null=True),
        ),
    ]
