# Generated by Django 3.0.1 on 2020-01-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrip', '0005_auto_20200120_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etype', models.CharField(max_length=50)),
            ],
        ),
    ]
