# Generated by Django 3.0.1 on 2020-01-25 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytrip', '0007_auto_20200126_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registration',
            name='evnt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mytrip.events'),
        ),
    ]
