# Generated by Django 3.0.1 on 2020-01-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytrip', '0008_event_registration_evnt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='lan',
            new_name='lng',
        ),
    ]
