# Generated by Django 3.0.1 on 2020-02-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrip', '0011_auto_20200216_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='photo',
            field=models.ImageField(default=None, upload_to='events'),
            preserve_default=False,
        ),
    ]
