# Generated by Django 3.0.1 on 2020-02-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrip', '0012_events_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.ImageField(default='', upload_to='media/event'),
        ),
    ]
