# Generated by Django 3.0.1 on 2020-02-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrip', '0013_auto_20200216_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.ImageField(default='', upload_to='events'),
        ),
    ]
